version: '3'
services:
  
    db-service:
        image: mongo:latest
        volumes:
            - ./mongo/mongod.conf:/etc/mongod.conf
        ports:
            - 27017:27017
        command: ["mongod"]
        networks: [oms]
    oms-service:
        image: gplugtest:latest
        depends_on: [db-service]
        ports:
            - 8090:8090
        networks: [oms]
    
networks:
    oms: